version: "3.9"
services:
  backend:
    image: ghcr.io/datarocks-ag/lwgs-person-data-processor-service:latest
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - internal
      - default
    volumes:
      - log-data:/var/log
      - hsqldb-data:/hsqldb/data
      - sedex:/var/sedex
    links:
      - rabbitmq
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      HSQLDB_FILE: "/hsqldb/data/searchindex-client"
      SEDEX_BASE_PATH: "/var/sedex"
      SEDEX_SENDER_ID: ${SEDEX_SENDER_ID}
      SEDEX_RECIPIENT_ID: ${SEDEX_RECIPIENT_ID}
      SEDEX_MESSAGE_TYPE: ${SEDEX_MESSAGE_TYPE}
      SEDEX_MESSAGE_CLASS: ${SEDEX_MESSAGE_CLASS}
      REST_API_KEY: ${REST_API_KEY}
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    networks:
      - default
      - internal
    ports:
      - "127.0.0.1:8082:15672"
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/conf.d/docker-presets.conf
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - rabbit-data:/var/lib/rabbitmq/mnesia/rabbit@lwgs-rabbit
      - rabbit-logs:/var/log/rabbitmq/log
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  prometheus:
    image: prom/prometheus
    restart: always
    networks:
      - internal
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - rabbitmq
      - backend
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "127.0.0.1:8081:3000"
    networks:
      - internal
      - default
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - ./docker/grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./docker/grafana/dashboards:/dashboards
    environment:
      GF_INSTALL_PLUGINS: "flant-statusmap-panel,grafana-piechart-panel"
    links:
      - prometheus
volumes:
  log-data: {}
  hsqldb-data: {}
  rabbit-data: {}
  rabbit-logs: {}
  grafana-data: {}
  sedex: {}
networks:
  internal: