version: "3.9"
services:
  backend:
    image: ghcr.io/datarocks-ag/lwgs-person-data-processor-service:latest
    restart: always
    ports:
      - 80:8080
    networks:
      - internal
      - default
    volumes:
      - logvolume:/var/log
      - dbvolume:/hsqldb/data
      - sedex:/var/sedex
    links:
      - rabbitmq
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      HSQLDB_FILE: "/hsqldb/data/searchindex-client"
      SEDEX_BASE_PATH: "/var/sedex"
      REST_API_KEY: ${REST_API_KEY}
      SEDEX_SENDER_ID: ${SEDEX_SENDER_ID}
      SEDEX_RECIPIENT_ID: ${SEDEX_RECIPIENT_ID}
      SEDEX_MESSAGE_TYPE: ${SEDEX_MESSAGE_TYPE}
      SEDEX_MESSAGE_CLASS: ${SEDEX_MESSAGE_CLASS}
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    networks:
      - internal
    volumes:
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@lwgs-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_PASSWORD}
  prometheus:
    image: prom/prometheus
    restart: always
    networks:
      - internal
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - rabbitmq
      - backend
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - internal
      - default
    links:
      - prometheus
volumes:
  logvolume: {}
  dbvolume: {}
  sedex: {}
networks:
  internal: