version: "3.9"
services:
  backend:
    build: .
    ports:
      - 80:8080
    volumes:
      - logvolume:/var/log
      - dbvolume:/hsqldb/data
    links:
      - rabbitmq
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      HSQLDB_FILE: "/hsqldb/data/searchindex-client"
      SEDEX_BASE_PATH: "/var/sedex"
      SEDEX_SENDER_ID: ${SEDEX_SENDER_ID}
      SEDEX_RECIPIENT_ID: ${SEDEX_RECIPIENT_ID}
      SEDEX_MESSAGE_TYPE: ${SEDEX_MESSAGE_TYPE}
      SEDEX_MESSAGE_CLASS: ${SEDEX_MESSAGE_CLASS}
      REST_API_KEY: ${REST_API_KEY}
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/conf.d/docker-presets.conf
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - rabbit-data:/var/lib/rabbitmq/mnesia/rabbit@lwgs-rabbit
      - rabbit-logs:/var/log/rabbitmq/log
  postgres:
    image: 'postgres:alpine'
    restart: always
    networks:
      - internal
      - default
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    profiles:
      - postgres
  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - rabbitmq
      - backend
  grafana:
    image: grafana/grafana
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - prometheus
volumes:
  logvolume: {}
  dbvolume: {}
